apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      securityContext:
        fsGroup: 65532
      volumes:
        - name: image-store
          persistentVolumeClaim:
            claimName: the-project-pvc
        - name: config-volume
          configMap:
            name: the-project-config
      initContainers:
        - name: fix-permissions
          image: alpine:3.20
          command: ["/bin/sh", "-c", "chown -R 65532:65532 /app/images && chmod 775 /app/images"]
          volumeMounts:
            - name: image-store
              mountPath: /app/images
      containers:
        - name: the-project
          image: the_project:2.6
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: PORT
