apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: the-project-svc
spec:
  selector:
    app: the-project # This is the app as declared in the deployment.
  ports:
    - name: http
      protocol: TCP
      port: 8080 # This is a port that is available to the cluster, in this case it can be ~ anything
      targetPort: 8080 # This is the target port
