apiVersion: batch/v1
kind: Job
metadata:
  name: todo-job-once
  namespace: project
spec:
  template:
    spec:
      containers:
      - name: todo-cronjob
        image: todo-cronjob:1.2
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
  backoffLimit: 4
