apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-output-svc
spec:
  type: NodePort
  selector:
    app: log-output # This is the app as declared in the deployment.
  ports:
    - name: http
      port: 80 # This is a port that is available to the cluster, in this case it can be ~ anything
      targetPort: 8080 # This is the target port
